### ISSUE TITLE
Add to the FreeCAD-addons repo for more streamlined installation

### ISSUE THREAD

**Issue by luzpaz** [cihologramas/freecad-pyoptools#1]
Open an issue up in https://github.com/FreeCAD/FreeCAD-addons to request adding this WB when you feel ready. Thanks. 
Also don't forget to give DeepSOIC a heads up regarding your work, see https://forum.freecadweb.org/viewtopic.php?t=7748

**Comment by luzpaz** [comment]
CC @DeepSOIC

**Comment by ramezquitao** [comment]
We will, 

Thanks

**Comment by luzpaz** [comment]
@ramezquitao any progress on this ?

**Comment by ramezquitao** [comment]
@luzpaz I'm sorry to say that we are a bit slow in that area. We use the WB regularly, but we haven't been able to finish it so it can be added to FC

**Comment by luzpaz** [comment]
perhaps there will be others that will like to help if you give them that chance...?

**Comment by ramezquitao** [comment]
Any help is welcome. But we haven't found anyone interested.

Another problem is that some times we are slow to answer. Not enough time :(

**Comment by luzpaz** [comment]
What dependencies does this workbench have? 
* FreeCAD version? 
* Python version? 
* 3rd party dependencies? 

We need to make a `package.xml` file: https://wiki.freecadweb.org/Package_Metadata

**Comment by ramezquitao** [comment]
I'm using it with FreeCAD 0.19 and 0.20 (but I use it mostly with 0.19 for the moment). About the python version, I use it with python 3.9 and 3.10. Any python 3 should work. The only dependency is to have pyoptools library installed (https://github.com/cihologramas/pyoptools). As this library is required, I was not able to run the workbench using the appimage version of FreeCAD. When this was tested, appimage - FreeCAD could not use the system installed libraries (I don know if this is still true).

**Comment by luzpaz** [comment]
Lets try. I'll start the process to get it ready for the addon manager. 
I need to 
- [x] add the https://github.com/cihologramas/pyoptools to the approved list of 3rd party dependencies for the addon manager. 
- [ ] create a `package.xml` file
