### ISSUE TITLE
Stray light analysis

### ISSUE THREAD

**Issue by ppfromero** [cihologramas/freecad-pyoptools#10]
Hi guys,

I'm searching for libraries to make optical design like: Lighttols, Opticstudio or RayJack One?
pyopttools seems to be perfect start point,  stray light analysis can be done?

Thanks

**Comment by ramezquitao** [comment]
Sorry, buy in its current state, pyoptools can not do stray light analysis, and for the moment it is not planed either. Any PR on this direction is welcome.

**Comment by ppfromero** [comment]
Ok Ricardo,
Thanks for this information I will continue to make some searching in internet, for the instance I see this package that can be very interesting:
https://github.com/bandang0/theia

Yo soy ecuatoriano trabajando por aca por Europa, que gusto que haya gente que trabaja en optica en Colombia!!

**Comment by ramezquitao** [comment]
Se hace lo que se puede, acá a la orden!!!

Por el momento voy a cerrar la petición.
