### ISSUE TITLE
addon installation not working

### ISSUE THREAD

**Issue by fariza** [cihologramas/freecad-pyoptools#3]
Cloning into `~/.FreeCAD/Mod` doesn't activate the addon

**Comment by luzpaz** [comment]
@fariza did you restart FreeCAD ?

**Comment by fariza** [comment]
Finally I was able to see an error
`During initialization the error cannot import name Component occurred in /home/fariza/.FreeCAD/Mod/freecad-pyoptools/InitGui.py`
If I try to import `InitGui.py` directly I get `ImportError: No module named FreeCAD`

Freecad version is `FreeCAD 0.16, Libs: 0.16R`

**Comment by ijpulidos** [comment]
@fariza  Just to let you know I'm reproducing this error in a fresh ubuntu LTS install with FreeCAD 0.15 it's not happening on a debian 8 machine with FreeCAD 0.17, no idea why is this happening.
I'll be investigating a little bit further to see the source of the error. Thanks for the report.

**Comment by ijpulidos** [comment]
@fariza Latest pyoptools changes solve this, there was something weird ocurring with the import of some new modules according to what @ramezquitao said to me(check https://github.com/cihologramas/pyoptools/commit/9e37c30339c87bb04e464297bf0d7a227e9615df). This is now all working on current ubuntuLTS, but you need latest FreeCAD (from git) for this to work correctly, I suggest you use the daily PPA if using ubuntu, more info at: https://www.freecadweb.org/wiki/Download#Ubuntu_Daily_PPA_Packages

**Comment by fariza** [comment]
With new installation of `freecad-daily` and fresh clone of `freecad-pyoptools`

Where is the log?


```
Run Gui init script
Init: Running FreeCADGuiInit.py start script...
Init:   Searching modules...
Init:      Initializing /usr/lib/freecad-daily/Mod/Sketcher... done
...
Init:      Initializing /usr/lib/freecad-daily/Mod/Material... done
Module: Part
Loading Part module... done
Init:      Initializing /home/fariza/.FreeCAD/Mod/freecad-pyoptools... failed
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
During initialization the error cannot import name Component occurred in /home/fariza/.FreeCAD/Mod/freecad-pyoptools/InitGui.py
Please look into the log file for further information
Init:      Initializing /usr/lib/freecad-daily/Mod/Raytracing... done
...
Init: Processing command line files
```

**Comment by ramezquitao** [comment]
The log is created in the .FreeCAD folder if you run freecad with -l flag

**Comment by ijpulidos** [comment]
@fariza you also need the latest pyoptools version, just in case.

**Comment by fariza** [comment]
After updating to master I get
`During initialization the error Non-ASCII character '\xc2' in file /home/fariza/.FreeCAD/Mod/freecad-pyoptools/pyOpToolsWB/raysparallel.py on line 74, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (raysparallel.py, line 74) occurred in /home/fariza/.FreeCAD/Mod/freecad-pyoptools/InitGui.py
Please look into the log file for further information`
If I change all the `mu` characters for `u` it start working but I don't know if this has a special meaning for unit conversion or if it is just the label

**Comment by ijpulidos** [comment]
@fariza This should be fixed now with changes in https://github.com/cihologramas/freecad-pyoptools/commit/0a4fc181436a52cc4d6a2dff30057b2bbb60ef10 . It was just a matter of defining the encoding for source files, I defined utf-8 for most (if not all) of them.
